import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsOut = resolve(here, "../../contracts/out");
const destination = resolve(here, "../src/index.ts");
const contracts = [
  "CreatorTokenValidator",
  "InterestRateModel",
  "MuseLendHedgeEpochVault",
  "MuseLendPositionManager",
  "MuseLendPositionReceipt",
  "MuseLendRiskManager",
  "MuseLendUSDCVault",
  "ProtocolTreasury",
  "UniswapV4SwapAdapter",
];

const entries = [];
for (const contract of contracts) {
  const artifactPath = resolve(contractsOut, `${contract}.sol/${contract}.json`);
  const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
  entries.push(`  ${contract}: ${JSON.stringify(artifact.abi)},`);
}

const source = [
  "// This file is generated by `pnpm --filter @muselend/abis generate`.",
  "// Do not edit contract fragments by hand.",
  "export const protocolAbis = {",
  ...entries,
  "} as const;",
  "",
].join("\n");

await writeFile(destination, source, "utf8");
