import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const contractsOut = resolve(here, "../../contracts/out");
const destination = resolve(here, "../src/index.ts");
const contracts = [
  "BaseCreatorTokenMirror",
  "BaseCreatorTokenMirrorFactory",
  "CreatorTokenValidator",
  "InterestRateModel",
  "MuseLendHedgeEpochVault",
  "MuseLendPositionManager",
  "MuseLendPositionReceipt",
  "MuseLendRiskManager",
  "MuseLendTestUSDC",
  "MuseLendUSDCVault",
  "ProtocolTreasury",
  "UniswapV4SwapAdapter",
];

const entries = [];
for (const contract of contracts) {
  const source = contract === "BaseCreatorTokenMirror" ? "BaseCreatorTokenMirrorFactory" : contract;
  const artifactPath = resolve(contractsOut, `${source}.sol/${contract}.json`);
  const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
  entries.push({ contract, abi: JSON.stringify(artifact.abi) });
}

const source = [
  "// This file is generated by `pnpm --filter @muselend/abis generate`.",
  "// Do not edit contract fragments by hand.",
  ...entries.map(({ contract, abi }) => `export const ${contract}Abi = ${abi} as const;`),
  "",
  "export const protocolAbis = {",
  ...entries.map(({ contract }) => `  ${contract}: ${contract}Abi,`),
  "} as const;",
  "",
].join("\n");

await writeFile(destination, source, "utf8");
